// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-1VjDKMUokWkztIsdQ15kucAFFS3LhJs',
    appId: '1:187136770481:web:892f91e514aeb7d8cf7d90',
    messagingSenderId: '187136770481',
    projectId: 'appointment-manager-5e9f7',
    authDomain: 'appointment-manager-5e9f7.firebaseapp.com',
    storageBucket: 'appointment-manager-5e9f7.firebasestorage.app',
    measurementId: 'G-CSHNXGP3TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo5_Wf4Q7H8-FcouzI6NyqMBGZnHu26MI',
    appId: '1:187136770481:android:5c760504d956ba7ccf7d90',
    messagingSenderId: '187136770481',
    projectId: 'appointment-manager-5e9f7',
    storageBucket: 'appointment-manager-5e9f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARF33d6GCV_1izLdFYxkb0ZKBgcBRml8o',
    appId: '1:187136770481:ios:ee351d86de785fc1cf7d90',
    messagingSenderId: '187136770481',
    projectId: 'appointment-manager-5e9f7',
    storageBucket: 'appointment-manager-5e9f7.firebasestorage.app',
    iosBundleId: 'com.sublimesoftwares.appointmentsManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARF33d6GCV_1izLdFYxkb0ZKBgcBRml8o',
    appId: '1:187136770481:ios:ee351d86de785fc1cf7d90',
    messagingSenderId: '187136770481',
    projectId: 'appointment-manager-5e9f7',
    storageBucket: 'appointment-manager-5e9f7.firebasestorage.app',
    iosBundleId: 'com.sublimesoftwares.appointmentsManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-1VjDKMUokWkztIsdQ15kucAFFS3LhJs',
    appId: '1:187136770481:web:4b253ceb48197dcdcf7d90',
    messagingSenderId: '187136770481',
    projectId: 'appointment-manager-5e9f7',
    authDomain: 'appointment-manager-5e9f7.firebaseapp.com',
    storageBucket: 'appointment-manager-5e9f7.firebasestorage.app',
    measurementId: 'G-J5SLGG4CTS',
  );
}
